# DRIVER_CHROME_PATH = 'chromedriver\\chromedriver.exe'
FILE_ALL_GOODS_JSON = 'data\\all_goods_list.json'
PATH_HTML_PAGES = 'data\\html'
RESULT_CSV = 'data\\result.csv'
FILE_DICT_FOR_SEARCH_ARTICLE = 'data\\dict_for_search_article.json'
